apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-sistema-deployment
spec:
  selector:
    matchLabels:
      name: aplicacao-sistema-pod
  template:
    metadata:
      labels:
        name: aplicacao-sistema-pod
    spec:
      containers:
        - name: container-aplicacao-sistema
          image: jnlucas/noticia-alura:v2
          ports:
            - containerPort: 80
