apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aplicacao-sistema-statefulset
spec:
  serviceName: aplicacao-sistema-statefulset
  selector:
    matchLabels:
      name: aplicacao-sistema-pod-statefulset
  template:
    metadata:
      labels:
        name: aplicacao-sistema-pod-statefulset
    spec:
      containers:
        - name: container-aplicacao-sistema-statefulset-v4
          image: jnlucas/noticia-alura:v4
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command: ["sh","enviarMensagens.sh"]

          volumeMounts:
            - name: imagens
              mountPath: /var/www/html/uploads
            - name: sessoes
              mountPath: /tmp
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: permissao-imagens
        - name: sessoes
          persistentVolumeClaim:
            claimName: permissao-sessao
